services:
  # Backend API service
  - type: web
    name: basketball-ref-api
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: basketball-ref-db
          property: connectionString
      # JWT Configuration
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      # Security Configuration
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: MAX_LOGIN_ATTEMPTS
        value: 5
      - key: LOCKOUT_TIME
        value: 15
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
      # Session Configuration
      - key: SESSION_CLEANUP_INTERVAL
        value: 3600000
      - key: MAX_SESSIONS_PER_USER
        value: 5
      # Server Configuration
      - key: PORT
        value: 3001

  # Frontend static site
  - type: web
    name: basketball-ref-client
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: basketball-ref-db
    databaseName: basketball_ref
    plan: free 