services:
  # Backend API service
  - type: web
    name: basketball-ref-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run deploy
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: basketball-ref-db
          property: connectionString

  # Frontend static site
  - type: web
    name: basketball-ref-client
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: basketball-ref-db
    databaseName: basketball_ref
    plan: free 